# Generated by Django 4.2 on 2024-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Language Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Country Name')),
                ('active_in_platform', models.BooleanField(default=False)),
                ('flag', models.URLField(blank=True, verbose_name='Flag Url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.ManyToManyField(related_name='cities', to='geo_app.city')),
            ],
        ),
    ]
